### ISSUE TITLE
Latest master errors

### ISSUE THREAD

**Issue by titvs** [MultiPoolMiner/MultiPoolMiner#1083]
I know the latest code has implementations that are work in progress but to help you guys, im including my logs that have a couple of errors:

[2018-01-20_15-50-00.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1648952/2018-01-20_15-50-00.txt)

Getting a lot of these errors (as well as others):

S>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again."

These errors dont show up on the main window. Just on the log.

I test your latest code on my test machine wich has a 1050Ti, plus a 1070.

I also got an error downloading Claymore CryptoNote CPU Miner. Had to download it manually and put it on the respective folder (and it isnt running on ready only mode).

Keep up the great work.

**Comment by UselessGuru** [comment]
> I also got an error downloading Claymore CryptoNote CPU Miner

This is expectcd behavior. There is currently no valid download link for version 3.9, thats why you have to download it manually.

> it isnt running on ready only mode

Fixed: https://github.com/MultiPoolMiner/MultiPoolMiner/commit/ee1fd0a9d8c5d22cbac96da64bec959dbc59d82b

**Comment by reticulator** [comment]
I see this thread was closed but have these errors in the log been fixed?

S>TerminatingError(Invoke-Expression): "The term '-r' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again."

I noticed these errors in the log as well, so I was watching this issue thread.  Now that it's closed, I pulled the latest master and I still see the same errors in the log.

**Comment by titvs** [comment]
The same here @reticulator ... Which gives a ver long log file... ;p I also have other errors as stated on the log file attached at the original message.

As for Cryptonote CPU Miner, @UselessGuru , I had to edit the miner file to put the - on the arguments field, since it was still not running on read only mode.

**Comment by reticulator** [comment]
So I did track the problem down to when the script invokes the Get-ChildItemContent function for the miner files.  Looks like it can get the .ps1 files just fine but when its working on the .txt files, it logs those exceptions.  That's about as far as i got in troubleshooting though.  I'm having kind of a hard time understanding how exactly that function is supposed to work.  What is supposed to do for .ps1 is pretty clear, but the .txt file processing is leaving me scratching my head a bit.  Some comments would be helpful.  Looks like some of that code was changed after the last release, so that might be the root cause.
