### ISSUE TITLE
Version 3.4.0 Beta 3 is ready

### ISSUE THREAD

**Issue by UselessGuru** [MultiPoolMiner/MultiPoolMiner#2343]
**Download link:**
https://github.com/UselessGuru/MultiPoolMiner/releases/download/3.4Beta-3/MultiPoolMiner.3.4.0.Beta3.zip

Please also report if all is working fine - only so I can know that we get rid of all the bugs.

#### Core Changes
- API: updated to version 0.94; added '/allminers'
- Added config item 'DevicePciOrderMapping' for configurations where PCI deviceID order does not match OpenCL deviceID order (see README)
- Parameters '-MinerName' and '-ExcludeMinerName' can be in one of the 3 forms: MinerBaseName e.g. 'AMD-TeamRed'; MinerBaseName_Version, e.g. 'AMD-TeamRed_v0.5.1' or MinerName, e.g. 'AMD-TeamRed_v0.5.1-1xEllesmere8GB'
- Rewrote interval & hashrate collector scheduler (again)
- Fixed error 'Method invocation failed because [XmRig] does not contain a method named 'op_Addition'.' (https://github.com/MultiPoolMiner/MultiPoolMiner/issues/2341#issuecomment-501782784)

#### Miner changes
- Fixed AMD_NVIDIA-BMiner_v15.5.3; device enumeration was broken in mixed rigs (AMD &NVIDIA in the same computer)
- Fixed miners Claymore*, Gminer, lolMinerEquihash, Nanominer, SRBMinerCryptonight & Wildrig; device enumeration can now use mapping as configured by 'DevicePciOrderMapping' 
- Updated AMD-TeamRed_v0.5.1; support for X16r, X16s & X16rt
- Updated AMD-WildRig_v0.17.5; support for Blake2b-BTCC & Blake2b-Glt
- Updated NVIDIA-CcminerTrex_v0.11.1
- Updated NVIDIA-NBMiner_v23.3

### Breaking changes

**Parameter '-UseDeviceNameForStatsFileNaming' is no longer valid**
This will trigger all benchmarks to be re-executed (unless you were running MPM with '-UseDeviceNameForStatsFileNaming:true' already)

**Comment by m-bosch** [comment]
errors during first run with installing new miners and benchmarking those miners:

```
You cannot call a method on a null-valued expression.
At C:\Users\x\Desktop\MultiPoolMiner-3.4.0-Beta3\MultiPoolMiner\MultiPoolMiner.ps1:1185 char:251
+ ... day (Earning: $($MiningEarning.ToString("N$($PowerPriceDigits)"))/day ...
+                                                 ~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : InvokeMethodOnNull
You cannot call a method on a null-valued expression.
At C:\Users\x\Desktop\MultiPoolMiner-3.4.0-Beta3\MultiPoolMiner\MultiPoolMiner.ps1:1185 char:251
+ ... day (Earning: $($MiningEarning.ToString("N$($PowerPriceDigits)"))/day ...
+                                                 ~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : InvokeMethodOnNull
```
and 
```
PS>TerminatingError(New-Object): "The member "Intervals" was not found for the specified .NET object."
New-Object : The member "Intervals" was not found for the specified .NET object.
At C:\Users\x\Desktop\MultiPoolMiner-3.4.0-Beta3\MultiPoolMiner\MultiPoolMiner.ps1:853 char:30
+             $ActiveMiners += New-Object $Miner.API -Property @{
+                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [New-Object], InvalidOperationException
+ FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.NewObjectCommand
New-Object : The member "Intervals" was not found for the specified .NET object.
At C:\Users\x\Desktop\MultiPoolMiner-3.4.0-Beta3\MultiPoolMiner\MultiPoolMiner.ps1:853 char:30
+             $ActiveMiners += New-Object $Miner.API -Property @{
+                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [New-Object], InvalidOperationException
+ FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.NewObjectCommand
```

**Comment by UselessGuru** [comment]
> errors during first run with installing new miners and benchmarking those miners:

Please try downloading again. Error should be gone.

**Comment by m-bosch** [comment]
please change the link on top of this topic from:
https://github.com/UselessGuru/MultiPoolMiner/archive/3.4.0-Beta3.zip

to the new link you made:
https://github.com/UselessGuru/MultiPoolMiner/archive/3.4.0.Beta3.zip

**Comment by UselessGuru** [comment]
> please change the link on top of this topic from:

Done

**Comment by smarcello** [comment]
On 3.4.0. beta 3:
Compare-Object : Cannot bind argument to parameter 'ReferenceObject' because it is null.
At F:\MINE\MultiPoolMiner\MultiPoolMiner.ps1:921 char:130
+ ... pare-Object ($_.Combination | Select-Object -ExpandProperty DeviceNam ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand

**Comment by UselessGuru** [comment]
> On 3.4.0. beta 3:
Compare-Object : Cannot bind argument to parameter 'ReferenceObject' because it is null.
At F:\MINE\MultiPoolMiner\MultiPoolMiner.ps1:921 char:130

Does this happen on each run?
I cannot understand why you are seeing this, nothing changed in that line... Is there someting special with you device / miner configuration? 
Could you please export `API/allminers` to a zip file and post it here?

**Comment by smarcello** [comment]
and it still happens for more than 45 minutes:
2019-06-15 12:41:41 INFO: Pinging monitoring server. Your miner status key is: xxxxx
2019-06-15 12:42:43 INFO: Miner Status (https://multipoolminer.io/monitor/miner.php): Success
what can be the problem??

**Comment by smarcello** [comment]
Sure, here it is:
[APIs.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/3292986/APIs.zip)

**Comment by UselessGuru** [comment]
> and it still happens for more than 45 minutes:

This problem is know - I am working on it right now.
Use this:
[MultiPoolMiner.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/3293091/MultiPoolMiner.zip)



> Could you please export API/allminers to a zip file and post it here?

Not the miner files. I need the output from the miner API (web GUI, e.g. http://localhost:3999/allminers).

**Comment by smarcello** [comment]
Sorry, here it is:
[allminers.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/3293351/allminers.zip)

**Comment by smarcello** [comment]
again, same thing with the new MultiPoolMiner.zip - ran for over 60 minutes
INFO: Pinging monitoring server. Your miner status key is: xxxxx
INFO: Miner Status (https://multipoolminer.io/monitor/miner.php): Success 
than system went down.....

**Comment by m-bosch** [comment]
No issues here after my fixed issue above. Great work @UselessGuru !

**Comment by smarcello** [comment]
yet, new red line st my place:
Start-Sleep : Cannot validate argument on parameter 'Seconds'. The -1 argument is less than the minimum allowed range of 0. Supply an argument that is greater than or equal to 0 and then try the command again.
At F:\MINE\MultiPoolMiner\MultiPoolMiner.ps1:1313 char:74
+ ... {Start-Sleep ((Get-Date).ToUniversalTime() - $NextPoll).TotalSeconds}
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Start-Sleep], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.StartSleepCommand

**Comment by smarcello** [comment]
and still limits without sense - attempt 319 of max,3 ?!
2019-06-18 06:06:29 WARNING: Benchmarking miner (AMD-WildRig_v0.17.5- {X16R@BlockMasters}) requires extended benchmark duration (Benchmarking interval 319/5) [Attempt 319 of max. 3].

**Comment by carlo0000** [comment]
bench of  nbminer don't work with 2 different gpu, it start 2 miners but

[08:02:07] INFO - ----------------------------------------------
[08:02:07] INFO - |                   NBMiner                  |
[08:02:07] INFO - |              NVIDIA GPU Miner              |
[08:02:07] INFO - |                    23.3                    |
[08:02:07] INFO - ----------------------------------------------
[08:02:07] INFO - ALGO:  cuckatoo
[08:02:07] INFO - ============= Device Information =============
[08:02:07] INFO - * ID 0: GeForce GTX 1070 8192 MB, CC 61
[08:02:07] INFO -   ID 1: GeForce GTX 1080 8192 MB, CC 61
[08:02:07] INFO - ==============================================
[08:02:07] INFO - NVML initialized.
[08:02:10] INFO - cuckatoo - Logging in to grincuckatoo31.eu.nicehash.com:3372 ...
[08:02:11] INFO - cuckatoo - Login succeeded.
[08:02:11] INFO - API:  127.0.0.1:4000
[08:02:11] INFO - API server started.
[08:02:11] INFO - cuckatoo - New job from grincuckatoo31.eu.nicehash.com, ID: 33696494, DIFF: 16.0
[08:02:13] INFO - Worker thread started on device 0.
[08:02:13] FATAL - Device 0, out of memory.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Mining program unexpected exit.
Reason: Process crashed
Restart miner after 10 secs ...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

[08:03:16] INFO - ----------------------------------------------
[08:03:16] INFO - |                   NBMiner                  |
[08:03:16] INFO - |              NVIDIA GPU Miner              |
[08:03:16] INFO - |                    23.3                    |
[08:03:16] INFO - ----------------------------------------------
[08:03:16] INFO - ALGO:  cuckatoo
[08:03:17] INFO - ============= Device Information =============
[08:03:17] INFO -   ID 0: GeForce GTX 1070 8192 MB, CC 61
[08:03:17] INFO - * ID 1: GeForce GTX 1080 8192 MB, CC 61
[08:03:17] INFO - ==============================================
[08:03:17] INFO - NVML initialized.
[08:03:20] INFO - cuckatoo - Logging in to grincuckatoo31.eu.nicehash.com:3372 ...
[08:03:20] INFO - cuckatoo - Login succeeded.
[08:03:20] INFO - API:  127.0.0.1:4001
[08:03:20] INFO - API server started.
[08:03:20] INFO - cuckatoo - New job from grincuckatoo31.eu.nicehash.com, ID: 33709482, DIFF: 16.0
[08:03:22] INFO - Worker thread started on device 1.
[08:03:22] FATAL - Device 1, out of memory.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Mining program unexpected exit.
Reason: Process crashed
Restart miner after 10 secs ...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by UselessGuru** [comment]
> and still limits without sense - attempt 319 of max,3 ?!

Thank you for your feedback. I am sorry for the inconvenience caused.
I am rewriting the scheduler.... I am getting there (slowly).

**Comment by UselessGuru** [comment]
> [08:03:22] INFO - Worker thread started on device 1.
> [08:03:22] FATAL - Device 1, out of memory.

Thank you for reporting.
In the next beta I'll increase the minimum memory for cuckatoo on win10 to 10GB (as listed in the miners readme.md).

**Comment by UselessGuru** [comment]
@smarcello 

Try this - it has the new scheduler:
[MultiPoolMiner.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/3308207/MultiPoolMiner.zip)

**Comment by smarcello** [comment]
Thanks @UselessGuru , trying that.
Bench-marking is very long and I find:
"Collected only 0 hash rate samples during last interval, configured number of samples is 10. If you see this message frequently then increase '-interval' time" - changed that to 100...

**Comment by UselessGuru** [comment]
To be continued here:
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/2345

**Comment by carlo0000** [comment]
NVIDIA-NBMiner_v23.3

only start gpu0 and not the others gpu's  (5x 1080ti)
